"""init

Revision ID: ae0b4b56f1b5
Revises: None
Create Date: 2016-07-10 16:56:26.379510

"""

# revision identifiers, used by Alembic.
revision = 'ae0b4b56f1b5'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('host',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=100), nullable=True),
    sa.Column('ip', sa.String(length=50), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('postion', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('host')
    ### end Alembic commands ###
